include ../../../common/common.inc.mk

ROOT_DIR:=$(abspath ../..)
ALGS_DIR:=$(abspath ..)

vpath %.c $(ALGS_DIR)/common

INCS+=-I$(ROOT_DIR)/include
INCS+=-I$(ALGS_DIR)/common
INCS+=-I$(CURDIR)

SRCS+=tx.c tx_util.c
LIBS+=-lpmemobj -lpmem

include ../../../common/Makefile.common