OBJS+=$(addprefix $(OUT_DIR)/,$(SRCS:.c=.o))

.PHONY: all
all: $(OBJS)

$(OUT_DIR)/%.o: %.c | $(OUT_DIR)
	$(CC) $(CFLAGS) $(LIBS) $(INCS) $< -o $@

$(OUT_DIR):
	mkdir -p $(OUT_DIR)

ifdef PROG
$(PROG): $(OBJS)
	$(CC) -o $@ $^ $(LIBS)

clean::
	rm -f $(PROG)
endif

.PHONY: clean
clean::
	rm -rf core.*
	rm -rf $(OUT_DIR)